//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BB.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Beacon
    {
        public System.Guid BeaconID { get; set; }
        public int Major { get; set; }
        public int Minor { get; set; }
        public Nullable<System.Guid> RoomID { get; set; }
    
        public virtual Room Room { get; set; }
    }
}
