//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BB.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lesson
    {
        public Lesson()
        {
            this.Sessions = new HashSet<Session>();
            this.Resources = new HashSet<Resource>();
            this.Courses = new HashSet<Course>();
        }
    
        public System.Guid LessonID { get; set; }
    
        public virtual ICollection<Session> Sessions { get; set; }
        public virtual ICollection<Resource> Resources { get; set; }
        public virtual ICollection<Course> Courses { get; set; }
    }
}
