//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BB.UnitOfWorkEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public System.Guid AttendanceID { get; set; }
        public System.Guid SessionID { get; set; }
        public System.Guid StudentID { get; set; }
    
        public virtual Session Session { get; set; }
        public virtual Student Student { get; set; }
    }
}
