//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BB.UnitOfWorkEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Module
    {
        public Module()
        {
            this.Courses = new HashSet<Course>();
            this.Sessions = new HashSet<Session>();
        }
    
        public System.Guid ModuleID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int TermNumber { get; set; }
    
        public virtual ICollection<Course> Courses { get; set; }
        public virtual ICollection<Session> Sessions { get; set; }
    }
}
