//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BB.UnitOfWorkEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public Session()
        {
            this.Lecturers = new HashSet<Lecturer>();
            this.Attendances = new HashSet<Attendance>();
        }
    
        public System.Guid SessionID { get; set; }
        public System.Guid LessonID { get; set; }
        public System.DateTime ScheduledStartDate { get; set; }
        public System.DateTime ScheduledEndDate { get; set; }
        public System.Guid RoomID { get; set; }
    
        public virtual Lesson Lesson { get; set; }
        public virtual Room Room { get; set; }
        public virtual ICollection<Lecturer> Lecturers { get; set; }
        public virtual ICollection<Attendance> Attendances { get; set; }
    }
}
